# Task 1: Data Cleaning and Modelling

In [35]:
import pandas as pd
import numpy as np

# Loding and Cleaning of content dataset

In [36]:
df_content=pd.read_csv("content.xls")

In [37]:
df_content

,Unnamed: 0,Content ID,User ID,Type,Category,URL
0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,https://socialbuzz.cdn.com/content/storage/975...
1,1,9f737e0a-3cdd-4d29-9d24-753f4e3be810,beb1f34e-7870-46d6-9fc7-2e12eb83ce43,photo,healthy eating,https://socialbuzz.cdn.com/content/storage/9f7...
2,2,230c4e4d-70c3-461d-b42c-ec09396efb3f,a5c65404-5894-4b87-82f2-d787cbee86b4,photo,healthy eating,https://socialbuzz.cdn.com/content/storage/230...
3,3,356fff80-da4d-4785-9f43-bc1261031dc6,9fb4ce88-fac1-406c-8544-1a899cee7aaf,photo,technology,https://socialbuzz.cdn.com/content/storage/356...
4,4,01ab84dd-6364-4236-abbb-3f237db77180,e206e31b-5f85-4964-b6ea-d7ee5324def1,video,food,https://socialbuzz.cdn.com/content/storage/01a...
...,...,...,...,...,...,...
995,995,b4cef9ef-627b-41d7-a051-5961b0204ebb,5b62e10e-3c19-4d28-a57c-e9bdc3d6758d,video,public speaking,NaN
996,996,7a79f4e4-3b7d-44dc-bdef-bc990740252c,4fe420fa-a193-4408-bd5d-62a020233609,GIF,technology,https://socialbuzz.cdn.com/content/storage/7a7...
997,997,435007a5-6261-4d8b-b0a4-55fdc189754b,35d6a1f3-e358-4d4b-8074-05f3b7f35c2a,audio,veganism,https://socialbuzz.cdn.com/content/storage/435...
998,998,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,b9bcd994-f000-4f6b-87fc-caae08acfaa1,GIF,culture,https://socialbuzz.cdn.com/content/storage/4e4...
999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,https://socialbuzz.cdn.com/content/storage/75d...

In [38]:
df_content.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1000 non-null   int64
 1   Content ID  1000 non-null   object
 2   User ID     1000 non-null   object
 3   Type        1000 non-null   object
 4   Category    1000 non-null   object
 5   URL         801 non-null    object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

In [39]:
for column in df_content.columns:
    if df_content[column].dtype=="object":
        print(f"Column: {column}")
        print(df_content[column].value_counts(dropna=False))
        print("\n")

Column: Content ID
Content ID
97522e57-d9ab-4bd6-97bf-c24d952602d2    1
d0c1d7f4-7735-49a9-ab6b-2cdb2338a609    1
22cdf77b-00c8-41c3-ad59-333c3e751e2c    1
28b8c278-a125-4295-98dd-5f8d45c3200b    1
e1792fe6-28e0-49fc-8b01-0e027461d8b5    1
                                       ..
16fb5dcb-4349-4831-acf2-8c116ad7dae5    1
0d5eb9fd-879d-4716-aebc-840f7b1b7e9f    1
e4827a5c-c604-4aad-b7ed-b396b3601b74    1
abecd821-ad3d-43b0-a550-aadd9d267072    1
75d6b589-7fae-4a6d-b0d0-752845150e56    1
Name: count, Length: 1000, dtype: int64


Column: User ID
User ID
72d2587e-8fae-4626-a73d-352e6465ba0f    8
3956593b-7739-426a-b7a5-e841c95a5df9    7
b473e898-b7b0-4a57-959d-484bf4cc4483    7
47def058-01cc-478f-9830-eaddcccac633    6
13f0db8a-152a-496f-a6e8-1ed6a90b8788    6
                                       ..
49f49bcf-17fe-4edd-990d-16c3d1df931b    1
b76ebf8d-3f04-4e7f-aec8-22575f68d9e2    1
6978b891-dea2-4217-8bc8-47d5aa25e743    1
9b6d35f9-5e15-4cd0-a8d7-b1f3340e02c4    1
fb4654ff-ce23-4a77-b52a-50f8948b5664    1
Name: count, Length: 446, dtype: int64


Column: Type
Type
photo    261
video    259
GIF      244
audio    236
Name: count, dtype: int64


Column: Category
Category
technology           71
animals              67
travel               67
culture              63
science              63
fitness              61
food                 61
healthy eating       61
cooking              60
soccer               58
tennis               58
education            57
dogs                 56
studying             55
veganism             48
public speaking      48
Fitness               5
Animals               4
Science               4
"soccer"              3
"culture"             3
Soccer                3
"dogs"                2
Education             2
Studying              2
Travel                2
Food                  2
"veganism"            1
"public speaking"     1
Public Speaking       1
"technology"          1
"cooking"             1
Healthy Eating        1
"studying"            1
"food"                1
Culture               1
"tennis"              1
Technology            1
"animals"             1
Veganism              1
"science"             1
Name: count, dtype: int64


Column: URL
URL
NaN                                                                                199
https://socialbuzz.cdn.com/content/storage/97522e57-d9ab-4bd6-97bf-c24d952602d2      1
https://socialbuzz.cdn.com/content/storage/f3e8d168-6fb9-48b9-8347-b35595162c1d      1
https://socialbuzz.cdn.com/content/storage/28b8c278-a125-4295-98dd-5f8d45c3200b      1
https://socialbuzz.cdn.com/content/storage/0c91753a-0bb4-4b77-a919-96c2f998ad91      1
                                                                                  ...
https://socialbuzz.cdn.com/content/storage/a39e8a86-63e3-4dcc-8561-4a0b7006df53      1
https://socialbuzz.cdn.com/content/storage/16fb5dcb-4349-4831-acf2-8c116ad7dae5      1
https://socialbuzz.cdn.com/content/storage/0d5eb9fd-879d-4716-aebc-840f7b1b7e9f      1
https://socialbuzz.cdn.com/content/storage/abecd821-ad3d-43b0-a550-aadd9d267072      1
https://socialbuzz.cdn.com/content/storage/75d6b589-7fae-4a6d-b0d0-752845150e56      1
Name: count, Length: 802, dtype: int64

In [40]:
df_content.duplicated().sum()

0

In [41]:
df_content.dropna(subset=['URL'], inplace=True)

In [42]:
df_content.info()

<class 'pandas.core.frame.DataFrame'>
Index: 801 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  801 non-null    int64
 1   Content ID  801 non-null    object
 2   User ID     801 non-null    object
 3   Type        801 non-null    object
 4   Category    801 non-null    object
 5   URL         801 non-null    object
dtypes: int64(1), object(5)
memory usage: 43.8+ KB

# Loding and Cleaning of Reaction dataset

In [43]:
df_reaction=pd.read_csv("Reactions.xls")

In [44]:
df_reaction

,Unnamed: 0,Content ID,User ID,Type,Datetime
0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,NaN,NaN,2021-04-22 15:17:15
1,1,97522e57-d9ab-4bd6-97bf-c24d952602d2,5d454588-283d-459d-915d-c48a2cb4c27f,disgust,2020-11-07 09:43:50
2,2,97522e57-d9ab-4bd6-97bf-c24d952602d2,92b87fa5-f271-43e0-af66-84fac21052e6,dislike,2021-06-17 12:22:51
3,3,97522e57-d9ab-4bd6-97bf-c24d952602d2,163daa38-8b77-48c9-9af6-37a6c1447ac2,scared,2021-04-18 05:13:58
4,4,97522e57-d9ab-4bd6-97bf-c24d952602d2,34e8add9-0206-47fd-a501-037b994650a2,disgust,2021-01-06 19:13:01
...,...,...,...,...,...
25548,25548,75d6b589-7fae-4a6d-b0d0-752845150e56,80c9ce48-46f9-4f5e-b3ca-3b698fc2e949,dislike,2020-06-27 09:46:48
25549,25549,75d6b589-7fae-4a6d-b0d0-752845150e56,2bd9c167-e06c-47c1-a978-3403d6724606,intrigued,2021-02-16 17:17:02
25550,25550,75d6b589-7fae-4a6d-b0d0-752845150e56,NaN,interested,2020-09-12 03:54:58
25551,25551,75d6b589-7fae-4a6d-b0d0-752845150e56,5ffd8b51-164e-47e2-885e-8b8c46eb63ed,worried,2020-11-04 20:08:31
25552,25552,75d6b589-7fae-4a6d-b0d0-752845150e56,4edc3d1a-a7d9-4db6-89c3-f784d9954172,cherish,2021-01-04 04:55:11

In [45]:
df_reaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25553 entries, 0 to 25552
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  25553 non-null  int64
 1   Content ID  25553 non-null  object
 2   User ID     22534 non-null  object
 3   Type        24573 non-null  object
 4   Datetime    25553 non-null  object
dtypes: int64(1), object(4)
memory usage: 998.3+ KB

In [46]:
df_reaction.dropna(subset=["Unnamed: 0","Content ID","Type","Datetime","User ID"],inplace=True)

In [47]:
df_reaction.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22534 entries, 1 to 25552
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  22534 non-null  int64
 1   Content ID  22534 non-null  object
 2   User ID     22534 non-null  object
 3   Type        22534 non-null  object
 4   Datetime    22534 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.0+ MB

# Loding and Cleaning of ReactionTypes dataset

In [48]:
df_reacttype=pd.read_csv("ReactionTypes.xls")

In [49]:
df_reacttype

    Unnamed: 0         Type Sentiment  Score
0            0        heart  positive     60
1            1         want  positive     70
2            2      disgust  negative      0
3            3         hate  negative      5
4            4   interested  positive     30
5            5  indifferent   neutral     20
6            6         love  positive     65
7            7   super love  positive     75
8            8      cherish  positive     70
9            9        adore  positive     72
10          10         like  positive     50
11          11      dislike  negative     10
12          12    intrigued  positive     45
13          13      peeking   neutral     35
14          14       scared  negative     15
15          15      worried  negative     12

In [50]:
df_reacttype.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  16 non-null     int64
 1   Type        16 non-null     object
 2   Sentiment   16 non-null     object
 3   Score       16 non-null     int64
dtypes: int64(2), object(2)
memory usage: 644.0+ bytes

# Merge all dataset

In [51]:
reaction_merged_df = pd.merge(df_reaction, df_reacttype, on='Type', how='left')

In [52]:
final_merged_df = pd.merge(reaction_merged_df,df_content, on='Content ID', how='left')

In [53]:
final_merged_df

,Unnamed: 0_x,Content ID,User ID_x,Type_x,Datetime,Unnamed: 0_y,Sentiment,Score,Unnamed: 0,User ID_y,Type_y,Category,URL
0,1,97522e57-d9ab-4bd6-97bf-c24d952602d2,5d454588-283d-459d-915d-c48a2cb4c27f,disgust,2020-11-07 09:43:50,2,negative,0,0.0,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,https://socialbuzz.cdn.com/content/storage/975...
1,2,97522e57-d9ab-4bd6-97bf-c24d952602d2,92b87fa5-f271-43e0-af66-84fac21052e6,dislike,2021-06-17 12:22:51,11,negative,10,0.0,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,https://socialbuzz.cdn.com/content/storage/975...
2,3,97522e57-d9ab-4bd6-97bf-c24d952602d2,163daa38-8b77-48c9-9af6-37a6c1447ac2,scared,2021-04-18 05:13:58,14,negative,15,0.0,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,https://socialbuzz.cdn.com/content/storage/975...
3,4,97522e57-d9ab-4bd6-97bf-c24d952602d2,34e8add9-0206-47fd-a501-037b994650a2,disgust,2021-01-06 19:13:01,2,negative,0,0.0,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,https://socialbuzz.cdn.com/content/storage/975...
4,5,97522e57-d9ab-4bd6-97bf-c24d952602d2,9b6d35f9-5e15-4cd0-a8d7-b1f3340e02c4,interested,2020-08-23 12:25:58,4,positive,30,0.0,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,https://socialbuzz.cdn.com/content/storage/975...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22529,25547,75d6b589-7fae-4a6d-b0d0-752845150e56,b6d04982-1509-41ab-a700-b390d6cb4d02,worried,2020-10-31 04:50:14,15,negative,12,999.0,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,https://socialbuzz.cdn.com/content/storage/75d...
22530,25548,75d6b589-7fae-4a6d-b0d0-752845150e56,80c9ce48-46f9-4f5e-b3ca-3b698fc2e949,dislike,2020-06-27 09:46:48,11,negative,10,999.0,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,https://socialbuzz.cdn.com/content/storage/75d...
22531,25549,75d6b589-7fae-4a6d-b0d0-752845150e56,2bd9c167-e06c-47c1-a978-3403d6724606,intrigued,2021-02-16 17:17:02,12,positive,45,999.0,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,https://socialbuzz.cdn.com/content/storage/75d...
22532,25551,75d6b589-7fae-4a6d-b0d0-752845150e56,5ffd8b51-164e-47e2-885e-8b8c46eb63ed,worried,2020-11-04 20:08:31,15,negative,12,999.0,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,https://socialbuzz.cdn.com/content/storage/75d...
22533,25552,75d6b589-7fae-4a6d-b0d0-752845150e56,4edc3d1a-a7d9-4db6-89c3-f784d9954172,cherish,2021-01-04 04:55:11,8,positive,70,999.0,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,https://socialbuzz.cdn.com/content/storage/75d...

In [54]:
final_merged_df=final_merged_df.drop(["Unnamed: 0","User ID_x","User ID_y","Unnamed: 0_y"],axis=1)

In [55]:
final_merged_df.rename(columns={'Type_x':'Reaction_type','Type_y':'Content_type'},inplace=True)

In [56]:
final_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22534 entries, 0 to 22533
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0_x   22534 non-null  int64
 1   Content ID     22534 non-null  object
 2   Reaction_type  22534 non-null  object
 3   Datetime       22534 non-null  object
 4   Sentiment      22534 non-null  object
 5   Score          22534 non-null  int64
 6   Content_type   18384 non-null  object
 7   Category       18384 non-null  object
 8   URL            18384 non-null  object
dtypes: int64(2), object(7)
memory usage: 1.5+ MB

In [57]:
final_merged_df = final_merged_df.dropna(subset=['Category', 'Content_type'])

In [58]:
final_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18384 entries, 0 to 22533
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0_x   18384 non-null  int64
 1   Content ID     18384 non-null  object
 2   Reaction_type  18384 non-null  object
 3   Datetime       18384 non-null  object
 4   Sentiment      18384 non-null  object
 5   Score          18384 non-null  int64
 6   Content_type   18384 non-null  object
 7   Category       18384 non-null  object
 8   URL            18384 non-null  object
dtypes: int64(2), object(7)
memory usage: 1.4+ MB

# Top 5 performing categories

In [59]:
final_merged_df['Performance Score'] = final_merged_df['Score']
category_performance = final_merged_df.groupby('Category')['Performance Score'].sum().reset_index()
top_categories = category_performance.sort_values(by='Performance Score', ascending=False).head(5)
print(top_categories)

          Category  Performance Score
15          travel              53935
10         science              53657
8   healthy eating              52745
1          animals              52443
2          cooking              49681

# Create excel file of merged dataset and Top 5 performing categories

In [60]:
with pd.ExcelWriter('final_output.xlsx') as writer:
    final_merged_df.to_excel(writer, sheet_name='Cleaned Dataset', index=False)
    top_categories.to_excel(writer, sheet_name='Top 5 Categories', index=False)